Changed python build versions.
There is an issue with the numpy version (1.12.1) used by the python 3.4
container in the travis-ci environment. Running unit tests there causes
an error like the following:

      File "/home/thomas/src/spectral/spectral/algorithms/detectors.py", line 561, in __call__
        return np.apply_along_axis(self, -1, X)
      File "/home/thomas/.virtualenvs/py34test/lib/python3.4/site-packages/numpy/lib/shape_base.py", line 91, in apply_along_axis
        res = func1d(arr[tuple(i.tolist())], *args, **kwargs)
      File "/home/thomas/src/spectral/spectral/algorithms/detectors.py", line 561, in __call__
        return np.apply_along_axis(self, -1, X)
      File "/home/thomas/.virtualenvs/py34test/lib/python3.4/site-packages/numpy/lib/shape_base.py", line 91, in apply_along_axis
        res = func1d(arr[tuple(i.tolist())], *args, **kwargs)
      File "/home/thomas/src/spectral/spectral/spectral.py", line 331, in __getitem__
        if isinstance(arg, numbers.Number):
      File "/home/thomas/.virtualenvs/py34test/lib/python3.4/abc.py", line 182, in __instancecheck__
        if subclass in cls._abc_cache:
      File "/home/thomas/.virtualenvs/py34test/lib/python3.4/_weakrefset.py", line 72, in __contains__
        wr = ref(item)
    RuntimeError: maximum recursion depth exceeded while calling a Python object

This error does not occur with new versions of numpy or other versions of python so
I am removing python 3.4 from the build list and added 3.5 and 3.6.